# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IPACatcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IPACatcher
#    pod 'SSZipArchive',:git => 'https://github.com/ZipArchive/ZipArchive.git'

end
